export const collections = {
  USER_COLLECTION: "user",
  PROFILE_COLLECTION: "profile",
  RACK_COLLECTIONS: "racks",
  SECTION_COLLECTION: "sections",
  ITEM_COLLECTION: "items",
  STOCK_COLLECTION: "stocks",
  UNIT_COLLECTION: "units",
  CATEGORY_COLLECTIONS: "categories",
  VENDOR_COLLECTIONS: "vendors",
  ACCOUNT_HEAD_COLLECTIONS: "account-heads",
  CUSTOMER_COLLECTIONS: "customers",
  TRANSACTIONS_COLLECTIONS: "CashTransactionS",
  BILL_COLLECTIONS:'bills',
  INVOICE_COLLECTIONS:"invoices",
  PAYMENT_COLLECTIONS:'payments',
  ACCOUNT_COLLECTION:'accounts',
  PREFIX_NUMBER_COLLECTION:'prefix',
  INVOICE_COLLECTIONS:'invoices'
}; 
